### ISSUE TITLE
1.1版本问题

### ISSUE THREAD

**Issue by benxiong** [qiushangzhe/tlow#1]
1.导出的css无法压缩
2.js无法做到热更
3.每次报错需要重新编译gulp
4.js每一步操作都需要重新gulp

**Comment by qiushangzhe** [comment]
已修复

**Comment by benxiong** [comment]
每次最最终压缩都要重新压缩一遍所有图片   略耗时   能否调整为特定命令压缩图片  因为不一定每次都要压缩    ~ o(*￣▽￣*)ブ
